#!/usr/bin/env bash
set -x
set -e
echo "chroot_priv_script - run chroot things that need runtime privilege"
export DEBIAN_FRONTEND=noninteractive

# such as network changes

mount none -t proc /proc
mount none -t sysfs /sys
mount none -t devpts /dev/pts
export HOME=/root
export LC_ALL=C

echo "Configure DNS resolution to 8.8.8.8"
dbus-uuidgen > /etc/machine-id
ln -fs /etc/machine-id /var/lib/dbus/machine-id

dpkg-divert --local --rename --add /sbin/initctl
ln -sf /bin/true /sbin/initctl

# dpkg-reconfigure -f noninteractive resolvconf

# Use resolv.conf to 8.8.8.8
mkdir -p /etc/NetworkManager
mv NetworkManager.conf /etc/NetworkManager
mv resolv.conf /etc
dpkg-reconfigure -f noninteractive network-manager

# Install xfce4 here
apt-get update
apt-get install -y \
    ssh \
    rsyslog \
    dbus \
    xfwm4 \
    xfce4 \
    xfce4-panel \
    xfce4-settings \
    xfconf \
    xfce4-terminal \
    xfce4-goodies \
    xfdesktop4 \
    xfce4-taskmanager \
    ubuntu-wallpapers

# sudo apt remove -y nautilus gnome-power-manager gnome-screensaver gnome-termina* gnome-pane* gnome-applet* gnome-bluetooth gnome-desktop* gnome-sessio* gnome-user* gnome-shell-common compiz compiz* unity unity* hud zeitgeist zeitgeist* python-zeitgeist libzeitgeist* activity-log-manager-common gnome-control-center gnome-screenshot overlay-scrollba*
apt-get remove -y gnome-session gnome gnome-shell
apt-get install -y xfce4-session

sudo apt-get -y autoremove

mv lightdm.conf /etc/lightdm/lightdm.conf
mkdir -p /home/ubuntu
addgroup ubuntu
adduser --disabled-password --gecos "" ubuntu --ingroup ubuntu
usermod -aG sudo ubuntu

chmod 0775 /home/ubuntu
chown ubuntu /home/ubuntu
chgrp ubuntu /home/ubuntu

# Install the SSH key
if [ -f ssh_key.pub ]; then
  mkdir -p /home/ubuntu/.ssh
  chmod 0700 /home/ubuntu/.ssh
  mv ssh_key.pub /home/ubuntu/.ssh/authorized_keys
  chmod 0600 /home/ubuntu/.ssh/authorized_keys
  chown -R ubuntu /home/ubuntu/.ssh
  chgrp -R ubuntu /home/ubuntu/.ssh
fi

truncate -s 0 /etc/machine-id

rm /sbin/initctl
dpkg-divert --rename --remove /sbin/initctl

echo "unmount"

umount /proc
umount /sys
umount /dev/pts
export HISTSIZE=0

echo "chroot_priv_script done"

